# Generated by Django 4.2.7 on 2024-06-20 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublicId', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('CompanyName', models.CharField(db_index=True, max_length=100, unique=True)),
                ('DateOfRegistration', models.DateField(null=True)),
                ('Address', models.CharField(max_length=100, unique=True)),
                ('NumberOfEmployees', models.IntegerField(default=1)),
                ('ContactPhone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Registration', models.CharField(default=None, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
