# Generated by Django 4.2.7 on 2024-06-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Registration',
            field=models.CharField(default=None, null=True, unique=True),
        ),
    ]
