# Generated by Django 4.2.7 on 2024-06-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Registered',
            field=models.BooleanField(default=False),
        ),
    ]
