# Generated by Django 4.2.7 on 2024-06-20 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublicId', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('EmployeeName', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Employed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
